site_name: MLCommons Science Working Group AI Benchmarks Collection
site_url: https://mlcommons-science.github.io/benchmarks
repo_url: https://github.com/mlcommons-science/benchmark/
repo_name: MLCommons Science Benchmarks

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.expand
    - content.code.copy
    - content.tabs.link

extra_css:
  - css/jquery.dataTables.min.css
  - css/fixedColumns.dataTables.min.css
  - css/custom.css

extra_javascript:
  - js/filters.js
  - js/jquery-3.7.1.min.js
  - js/jquery.dataTables.min.js
  - js/dataTables.fixedColumns.min.js


# enable niceties used by the cleaner layout
markdown_extensions:
  - pymdownx.superfences
  - footnotes

nav:
  - index.md
  - Report: benchmarks.pdf
  - List: md/benchmarks/index.md
  - Table: md/benchmarks_table.md
  - Cards: md/benchmarks/cards.md
